- debian/control
- qimage-plugins/qimage-plugins.pro
drop freeimage plugin and recommend plugins provides by kimageformats
as suggested in https://github.com/linuxdeepin/deepin-image-viewer/issues/2
> fix: freeimage plugin caused crash

- viewer/module/view/navigationwidget.cpp
- viewer/module/view/navigationwidget.h
- viewer/module/view/scen/imageview.cpp
when the image content coordinates are 0,0
https://github.com/linuxdeepin/internal-discussion/issues/1680
> fix: the image content navigation widget not visible

- src/src/mainwindow/mainwindow.cpp
- src/src/mainwindow/mainwindow.h
Description: 卡顿是因为频繁的设置配置，现在改为最后一次设置
Log: 与配置设置有关
Bug: https://pms.uniontech.com/bug-view-134951.html
> fix: 修复bug134951

- src/src/mainwindow/mainwindow.cpp
- src/src/module/view/homepagewidget.cpp
避免使用相对路径引用 libimageviewer 的头文件
Resolve: https://github.com/linuxdeepin/developer-center/issues/2237
> chore: including headers from libimageviewer

- debian/rules
删除构建的多余参数以适配新版cmake
Log: 删除构建的多余参数以适配新版cmake
> fix: 删除构建的多余参数以适配新版cmake

- src/CMakeLists.txt
- src/src/main.cpp
Description: 看图DBus服务未注册，导致DBus send未正常获取应答，添加注册看图服务，后续添加看图DBus接口。
Log: 修复连续使用DBus启动看图无法正常启动的问题
Influence: DBus调用
> fix: 修复连续使用DBus启动看图无法正常启动的问题

- src/src/main.cpp
Description: 问题是初次打开看图时，代码基于桌面的宽度计算控件宽度，而非基于屏幕显示的宽度，导致界面计算超过一个屏幕。修改为根据主屏的宽度进行计算。 需要注意屏幕部分接口在Qt5.11后弃用，调整为兼容接口。
Log: 修复双屏拓展模式，打开看图，界面显示超过一个屏幕问题
Bug: https://pms.uniontech.com/bug-view-168259.html
Influence: 初始化界面大小
> fix: 修复双屏拓展模式，打开看图，界面显示超过一个屏幕问题

- src/src/mainwindow/mainwindow.cpp
弹窗设置图片后，窗口切换，焦点可能丢失，导致不响应快捷键。
修改为弹窗设置后强制更新窗口焦点。
Log: 修复打开图片后焦点丢失，快捷键失效问题
Bug: https://pms.uniontech.com/bug-view-185519.html
Influence: 设置图片后的焦点切换
> fix: 修复打开图片后焦点丢失，快捷键失效问题

- src/com.deepin.imageViewer.service
为保证在其他上游正常构建，恢复为deepin-image-viewer来启动看图，在下一笔提交中使用patch补丁设置玲珑环境下用玲珑命令启动看图
Log: 去掉DBus服务玲珑命令相关配置
> chore: 去掉DBus服务玲珑命令相关配置

- src/com.deepin.imageViewer.service
为保证在其他上游正常构建，恢复为deepin-image-viewer来启动看图，在下一笔提交中使用patch补丁设置玲珑环境下用玲珑命令启动看图
Log: 去掉DBus服务玲珑命令相关配置
> chore: 去掉DBus服务玲珑命令相关配置 (#130)

- src/assets/deepin-image-viewer/image-viewer/en_US/d_image-viewer.md
- src/assets/deepin-image-viewer/image-viewer/en_US/image-viewer.md
- src/assets/deepin-image-viewer/image-viewer/zh_CN/d_image-viewer.md
- src/assets/deepin-image-viewer/image-viewer/zh_CN/image-viewer.md
- src/assets/deepin-image-viewer/image-viewer/zh_HK/d_image-viewer.md
- src/assets/deepin-image-viewer/image-viewer/zh_HK/image-viewer.md
- src/assets/deepin-image-viewer/image-viewer/zh_TW/d_image-viewer.md
- src/assets/deepin-image-viewer/image-viewer/zh_TW/image-viewer.md
删除md文件中多余的开源合规注释，以便帮助手册能正确解析md文件找到应用图标名称和位置
Log: 修复看图应用图标在帮助手册显示为撕裂图的问题
Bug: https://pms.uniontech.com/bug-view-183623.html
> fix: 修复看图应用图标在帮助手册显示为撕裂图的问题

- src/qml/ViewTopTitle.qml
It is a bug for `dtkdeclarative`, but we can avoid it.
Issue: https://github.com/linuxdeepin/developer-center/issues/4222
> fix: AboutDialog's titlebar tearing shadow

- debian/changelog
Update version to 6.0.2
相关PR：
* https://github.com/linuxdeepin/deepin-image-viewer/pull/140
Log: Update version to 6.0.2
> chore: Update version to 6.0.2

- debian/control
看图拆分 libxraw 后，补充安装依赖 libxraw，
以规避自旧版本升级看图时，无法正常安装及处理RAW格式图片,
看图 5.9.11 后版本不兼容，使用 Conficts 强制重新安装,
libxraw 使用 Replaces 安装 5.9.11 之前的包内容(libxraw.so库)
Log: 添加安装依赖libxraw
Bug: https://pms.uniontech.com/bug-view-199143.html
Influence: 安装依赖libxraw
> chore: 添加安装依赖libxraw

- debian/changelog
Update version to 5.9.12
主要拆分看图 libxraw 插件为两个包
相关PR:
* https://github.com/linuxdeepin/deepin-image-viewer/pull/142
* https://github.com/linuxdeepin/deepin-image-viewer/pull/145
Log: Update version to 5.9.12
> chore: Update version to 5.9.12

- src/src/mainwindow/mainwindow.cpp
DTK 在 5.6.4 版本提供紧凑模式,适配紧凑模式,
动态调整标题栏高度和位置.
旧版设置固定高度,在模式变更时被 DTK 设置覆盖,
修改为使用 setVisible() 接口.
Log: Adapt compact mode.
Bug: https://pms.uniontech.com/bug-view-199309.html
Influence: TitleBar CompactMode
> fix: Adapt compact mode.

- src/src/main.cpp
点击图片打开时，show() 重置了窗口状态，重新设置标题栏模式。
Log: Adapt comapct mode with click image.
Bug: https://pms.uniontech.com/bug-view-199309.html
Influence: ComapctMode
> fix: Adapt comapct mode with click image.

- debian/changelog
Update version to 5.9.13
适配紧凑模式
相关PR：
* https://github.com/linuxdeepin/deepin-image-viewer/pull/147
* https://github.com/linuxdeepin/deepin-image-viewer/pull/147
Log: Update version to 5.9.13
> chore: Update version to 5.9.13

- debian/control
回退应分级管控引入的安装依赖关系
image-viewer 中途拆分 libxraw 软件包，为兼容升级处理，
对低于 5.9.14 版本的软件包进行替换处理。
Log: 兼容旧版本拆分的 libxraw 软件包.
Influence: Debian/Control
> Revert "chore: 添加安装依赖libxraw"

- qimage-plugins/libraw/rawiohandler.cpp
libraw 库在0.21.0版本变更了`libraw_data_t`结构,
移动`use_rawspeed`至`libraw_raw_unpack_params_t`,
添加版本分支以兼容 0.21.0 或更低版本.
Log: 修复 0.21.0 及更高版本的 libraw 编译问题
Influence: RAW
> fix: build failed with libraw after version 0.21.0

- src/main.cpp
看图应用使用Qt::AA_UseHighDpiPixmaps属性
Log: 修复高分屏图标显示过大的问题
Issue: linuxdeepin/developer-center#4884
> fix: 修复高分屏图标显示过大的问题

- src/qml/ImageViewer.qml
右键菜单在调用换灯片播放后，当前图片展示组件将被销毁，
但未复位 showRightMenu 属性，二次创建时菜单无法正常展示。
添加菜单销毁复位 showRightMenu 属性。
Log: 修复幻灯片播放后，右键菜单丢失
Bug: https://pms.uniontech.com/bug-view-208417.html
Influence: RightClickMenu
> fix: The right-click menu disappears after slideshow.

- debian/changelog
- qimage-plugins/libraw/rawiohandler.cpp
Fix build failed with libraw after version 0.21.0
Bump version to 5.9.15
PR:
* https://github.com/linuxdeepin/deepin-image-viewer/pull/158
Log: Bump version to 5.9.15
> chore: Fix bug and Bump version to 5.9.15

- src/src/module/view/homepagewidget.cpp
修复打开图片缺省图位置不居中.
Log: 修复打开图片缺省图位置不居中.
Bug: https://pms.uniontech.com/bug-view-156713.html
Influence: UI
> fix: Not layout center on OpenImage widget.

- src/src/main.cpp
These header files are no longer implicitly included in Qt 5.15, add them.
Log: Add implicitly included header files
> fix: Add implicitly included header files

- debian/changelog
Bump version to 5.9.17
PR:
* https://github.com/linuxdeepin/deepin-image-viewer/pull/160
* https://github.com/linuxdeepin/deepin-image-viewer/pull/161
* https://github.com/linuxdeepin/deepin-image-viewer/pull/162
Log: Bump version to 5.9.17
> chore: Bump version to 5.9.17

- src/src/mainwindow/mainwindow.cpp
调整默认快捷键浮窗弹出位置.
现在将显示在焦点屏幕(光标所在屏幕)中央.
Log: 调整默认快捷键浮窗弹出位置
Task: https://pms.uniontech.com/task-view-332273.html
Influence: Shortcuts
> feat: Change default shortcuts popup position

- debian/changelog
Bump version to 5.9.18
PR:
* https://github.com/linuxdeepin/deepin-image-viewer/pull/164
Log: Bump version to 5.9.18
> chore: Bump version to 5.9.18

- .tx/config
- debian/control
- src/CMakeLists.txt
- src/misc/context-menus/deepin-print-pictures.conf
- src/src/application.cpp
- src/src/application.h
- src/src/main.cpp
- src/translations/context-menus/deepin-print-pictures.ts
- src/translations/context-menus/deepin-print-pictures_bo.ts
- src/translations/context-menus/deepin-print-pictures_ug.ts
- src/translations/context-menus/deepin-print-pictures_zh_CN.ts
- src/translations/context-menus/deepin-print-pictures_zh_HK.ts
- src/translations/context-menus/deepin-print-pictures_zh_TW.ts
- src/translations/deepin-image-viewer_he.ts
- src/translations/deepin-image-viewer_hr.ts
- src/translations/deepin-image-viewer_nl.ts
> feat: 添加批量打印功能

- src/main.cpp
- src/qml/ImageViewer.qml
- src/qml/ThumbnailListView.qml
- src/src/imagedata/imageinfo.cpp
- src/src/imagedata/imageinfo.h
- src/src/imagedata/imageprovider.cpp
- src/src/imagedata/imageprovider.h
优化图像加载策略,旧版代码 Delegate 依赖外部ListView
的组件大小,导致ListView计算时会遍历元素导致加载关联
图片的缩略图.
调整加载策略,避免启动后无关的加载,将首张图片加载优先
级提前.
Log: 修复部分启动问题
> fix: Improve image load policy

- src/qml/FullImageView.qml
- src/qml/ImageDelegate/NonexistImageDelegate.qml
- src/qml/ImageViewer.qml
- src/qml/InformationDialog/InformationDialog.qml
- src/qml/InformationDialog/PropertyActionItemDelegate.qml
- src/qml/InformationDialog/PropertyItem.qml
- src/qml/InformationDialog/PropertyItemDelegate.qml
- src/qml/ViewTopTitle.qml
- src/qml/main.qml
- src/src/globalcontrol.h
[fix: style for not-existent images](https://github.com/linuxdeepin/deepin-image-viewer/commit/949d7377c8ee0f470f5457169cc814e69a203179) 
Fixed style for not-existent images.
Log: Fixed style for not-existent images
Bug: https://pms.uniontech.com/bug-view-213323.html
[fix: information dialog layout](https://github.com/linuxdeepin/deepin-image-viewer/commit/f5226c3aa9a4b0d1286ce695c656b5f1a51201f4) 
* Update information dialog layout;
* Update font size and palette.
Log: Fix information dialog layout
Bug: https://pms.uniontech.com/bug-view-168015.html
[fix: live text button position and palette](https://github.com/linuxdeepin/deepin-image-viewer/pull/173/commits/6528512a519d6122de80df4339b3919d90755e02) 
As titile.
Log: Fixed live text button position and palette
Bug: …
> fix: style for not-existent images and information dialog

- src/deepin-image-viewer.qrc
- src/main.cpp
- src/qml/Dialog/RemoveDialog.qml
- src/qml/ImageDelegate/DamagedImageDelegate.qml
- src/qml/ReName.qml
- src/qml/ThumbnailListView.qml
- src/src/filecontrol.cpp
- src/src/imagedata/imagefilewatcher.cpp
- src/src/imagedata/imagefilewatcher.h
- src/src/utils/filetrashhelper.cpp
- src/src/utils/filetrashhelper.h
- src/translations/deepin-image-viewer.ts
- src/translations/deepin-image-viewer_bo.ts
- src/translations/deepin-image-viewer_ug.ts
- src/translations/deepin-image-viewer_zh_CN.ts
- src/translations/deepin-image-viewer_zh_HK.ts
- src/translations/deepin-image-viewer_zh_TW.ts
Add delete dialog component;
Copy the device type detection code from DFM.
Log: Add delete confirmation dialog
Bug: https://pms.uniontech.com/bug-view-167807.html
> Fix: add delete confirmation dialog

- src/qml/NavigationWidget.qml
- src/qml/ViewRightMenu.qml
- src/src/filecontrol.cpp
fix navigation not update while image rotate.
Log: fix navigation not update while image rotate.
Influence: Animation
> fix: navigation not update while image rotate

- src/qml/ImageViewer.qml
- src/qml/InformationDialog/PropertyActionItemDelegate.qml
- src/qml/InformationDialog/PropertyItemDelegate.qml
- src/src/filecontrol.cpp
- src/src/imagedata/pathviewproxymodel.cpp
[fix: ui/ocr/reinit error](https://github.com/linuxdeepin/deepin-image-viewer/pull/182/commits/c57dc6db8820869bd12be3b415651021b650e47d) 
Adjust information dialog label padding;
Init PathView currentIndex when component completed;
Adjust ocr cache folder.
Log: Fix some known errors.
Bug: https://pms.uniontech.com/bug-view-268607.html
> fix: ui/ocr/reinitialization error

- src/src/mainwindow/mainwindow.cpp
remove bash use
Log: remove bash use
Task: https://pms.uniontech.com/task-view-362321.html
> fix:[cmd] remove bash use

- src/main.cpp
- src/qml/MainStack.qml
- src/src/filecontrol.cpp
- src/src/filecontrol.h
- src/src/utils/filetrashhelper.cpp
- src/src/utils/filetrashhelper.h
[fix: shortcut and log file](https://github.com/linuxdeepin/deepin-image-viewer/commit/5f6534583ffa340b1663c07aa205431a3188756a) 
* Fix open help shortcut;
* Set default open file folder;
* Add log file.
Log: Fix some issue.
Bug: https://pms.uniontech.com/bug-view-273543.html
[fix: error pop-up deletion dialog](https://github.com/linuxdeepin/deepin-image-viewer/commit/7735a3d815348980d0dcb383fb89ee3f45d68750) 
The timeout is too short, and the file manager
backend cannot complete the image deletion.
This causes an error dialog to pop up.
Log: Fix error pop-up deletion dialog.
Bug: https://pms.uniontech.com/bug-view-273813.html
> Fix: error shortcut and pop-up deletion dialog

- src/qml/ImageViewer.qml
- src/qml/MainStack.qml
as title.
Enable pop-up shortcut panel on main window.
Log: Fix shortcut issue.
Bug: https://pms.uniontech.com/bug-view-273543.html
> fix: move show shortcut panel to mainwindow

- src/qml/main.qml
- src/src/globalcontrol.cpp
- src/src/globalcontrol.h
Fixed the issue of waiting for restart after exiting
Bug: https://pms.uniontech.com/bug-view-289921.html
Log: Fixed the issue of waiting for restart after exiting
> fix: Fixed the issue of waiting for restart after exiting

- src/qml/LiveText/LiveBlock.qml
- src/src/ocr/livetextanalyzer.cpp
- src/src/ocr/livetextanalyzer.h
- Add devicePixelRatio support to fix text box positioning on HiDPI screens
- Remove Image.Tile fillMode for better DPI compatibility
- Scale image dimensions based on device pixel ratio
Log: Fix ocr position offset on HiDPI displays.
Bug: https://pms.uniontech.com/bug-view-275403.html
> fix: ocr position offset on HiDPI displays

- .gitignore
- arm64/linglong.yaml
- deploy_dep
- install_dep
- linglong.yaml
- loong64/linglong.yaml
Enable linglong build with Qt6.8 runtime.
Log: Enable linglong build with Qt6.8 runtime.
> chore: Support linglong building base on Qt6.8 runtime

- src/CMakeLists.txt
- src/main.cpp
- src/misc/context-menus/deepin-print-pictures.conf
- src/src/commandparser.cpp
- src/src/commandparser.h
Implement command-line parsing functionality:
- Create CommandParser class to handle command-line arguments
- Add support for quick printing via "-print" option
- Integrate command-line parsing in main application startup
- Install context-menu configuration file for print functionality
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-303741.html
> fix: Add command-line support for quick printing

- src/src/ocr/livetextanalyzer.cpp
Loong64 with llvm are temporarily unstable,
disable GPU for now.
Log: fix a crash issue
Bug: https://pms.uniontech.com/bug-view-304463.html
> fix: ocr crash on loongarch

- src/main.cpp
Description:
- Remove TODO comment about DTK6 menu display issue as it's no longer relevant
- Set application organization name to 'deepin' for better identification
Log: Set application organization name
> fix: Set organization name and remove obsolete comment

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
Bump version in configuration files to 6.0.21 for deepin-image-viewer.
Log: Updated version to 6.0.21 in linglong.yaml and debian/changelog.
> chore: Update version to 6.0.21
