README.md
viewer/module/view/contents/imageinfowidget.cpp
viewer/translations/deepin-image-viewer.ts
viewer/widgets/dialogs/imginfodialog.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1269

chore: translation update.

---

viewer/module/album/imagesview.cpp
viewer/module/timeline/timelinepanel_menu.cpp
viewer/module/view/viewpanel.cpp
viewer/module/view/viewpanel_menu.cpp
viewer/widgets/printhelper.cpp

fix: not using color printing even if printers supports it

---

viewer/utils/baseutils.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1412
@electricface

fix: can not copy images to windows applications

---

.gitignore
viewer/module/view/scen/imageview.cpp

chore: remove unused code

---

viewer/widgets/printhelper.cpp

Fix setting print parameters in print preview is invalid
https://github.com/linuxdeepin/internal-discussion/issues/1733

fix: use QPrintPropertiesDialog replace QPageSetupDialog

---

viewer/widgets/printoptionspage.cpp

Add missing return function

---

viewer/frame/toptoolbar.cpp
viewer/module/view/contents/imageinfowidget.cpp
viewer/module/view/contents/ttbcontent.cpp

build failures under Qt 5.15
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

fix: build failures under Qt 5.15

---

viewer/utils/unionimage.cpp

Correct some typos
Log: correct some typos

chore: correct some typos

---

debian/changelog
debian/rules

fix: 修改V20构建配置

---

debian/changelog

fix: keep changelog version format and format the same

---

src/src/main.cpp
src/src/utils/eventlogutils.cpp
src/src/utils/eventlogutils.h

Description: 提交埋点需求，采集看图启动数据
Log: 提交埋点需求，采集看图启动数据

feat: 提交埋点需求，采集看图启动数据

---

.reuse/dep5
LICENSES/CC-BY-4.0.txt
LICENSES/CC0-1.0.txt
LICENSES/GPL-3.0-or-later.txt
README.zh_CN.md
qimage-plugins/libraw/datastream.cpp
qimage-plugins/libraw/main.cpp
qimage-plugins/libraw/rawiohandler.cpp
src/src/accessibility/ac-desktop-define.h
src/src/application.cpp
src/src/application.h
src/src/main.cpp
src/src/mainwindow/mainwindow.cpp
src/src/mainwindow/mainwindow.h
src/src/module/view/homepagewidget.cpp
src/src/module/view/homepagewidget.h
src/src/utils/eventlogutils.cpp
src/src/utils/eventlogutils.h
tests/gtestview.cpp
tests/gtestview.h
tests/main.cpp
tests/testapi.h

Description: Adapt REUSE license
Log: Adapt REUSE license
Influence: Adapt REUSE license

chore: Adapt REUSE license

---

debian/control
src/src/mainwindow/mainwindow.cpp
src/src/mainwindow/mainwindow.h

修复未安装deepin-ocr时，快捷键面板会提示OCR的快捷键
Log: 修复未安装deepin-ocr时，快捷键面板会提示OCR的快捷键

fix: 修复未安装deepin-ocr时，快捷键面板会提示OCR的快捷键

---

.reuse/dep5
qimage-plugins/libraw/main.cpp
qimage-plugins/libraw/rawiohandler.cpp
src/CMakeLists.txt
src/com.deepin.imageViewer.service
src/main.cpp
src/qml/ImageViewer.qml
src/qml/OpenImageWidget.qml
src/qml/ThumbnailListView.qml
src/qml/ViewTopTitle.qml
src/src/dbus/applicationadpator.cpp
src/src/dbus/applicationadpator.h
src/src/filecontrol.cpp
src/src/filecontrol.h

fix: 合并V23修复bug

---

src/src/filecontrol.cpp

Description: 调整部分修改的DBus接口使用方式，以同时处理V20和V23的接口调用
Log: 适配V23 DDE DBus接口
Influence: DBus接口

feat: 适配V23 DDE DBus接口

---

src/src/filecontrol.cpp

Description: 添加详细的DBus调用日志信息
Log: 添加DBus调用日志

style: 添加DBus调用日志

---

.tx/deepin.conf
debian/changelog

Update version to 5.9.10
Log: Update version to 5.9.10

chore: Update version to 5.9.10

---

.reuse/dep5
linglong.yaml
patches/fix-linglong.patch

添加玲珑构建patch补丁，用于设置玲珑环境看图DBus服务
Log: 添加玲珑构建patch补丁，用于设置玲珑环境看图DBus服务

chore: 添加玲珑构建patch补丁，用于设置玲珑环境看图DBus服务

---

debian/changelog

Update version to distinguish pro/community.
Log: Update version to 5.9.11

chore: Update version to 5.9.11

---

debian/changelog

update V6.0.1
Log: update V6.0.1

chore: update V6.0.1

---

debian/changelog

Update version to 5.9.14
PR：
* https://github.com/linuxdeepin/deepin-image-viewer/pull/152
* https://github.com/linuxdeepin/deepin-image-viewer/pull/153
Log: Update version to 5.9.14

chore: Update version to 5.9.14

---

debian/changelog

[Community] Bump version to 5.9.16 for diff branch
Log: [Community] Bump version to 5.9.16

chore: [Community] Bump version to 5.9.16

---

debian/changelog

Bump version to 5.9.19
Log: Bump version to 5.9.19

chore: Bump version to 5.9.19

---

src/qml/InformationDialog/PropertyActionItemDelegate.qml
src/qml/InformationDialog/PropertyItemDelegate.qml
src/qml/OpenImageWidget.qml

adjust openimagewidget and dialog layout.
Log: fix some ui issue.

fix: adjust openimagewidget and dialog layout

---

src/qml/ImageDelegate/DamagedImageDelegate.qml
src/qml/NavigationWidget.qml
src/qml/ViewRightMenu.qml

* Navigation auto-hides at minimum size;
* Disable navigation right menu item at minimum size;
* Reaplce ActionButton with DciIcon.
Log: fix some ui issue
Bug: https://pms.uniontech.com/bug-view-167955.html

fix: navigation and right menu

---

src/deepin-image-viewer.qrc
src/main.cpp
src/qml/FullImageView.qml
src/qml/ImageDelegate/BaseImageDelegate.qml
src/qml/ImageDelegate/DamagedImageDelegate.qml
src/qml/ImageDelegate/NonexistImageDelegate.qml
src/qml/ImageDelegate/NormalImageDelegate.qml
src/qml/ImageDelegate/ViewDelegateLoader.qml
src/qml/ImageViewer.qml
src/qml/ThumbnailDelegate/BaseThumbnailDelegate.qml
src/qml/ThumbnailDelegate/MultiThumnailDelegate.qml
src/qml/ThumbnailDelegate/NormalThumbnailDelegate.qml
src/qml/ThumbnailDelegate/ThumbnailImage.qml
src/qml/ThumbnailListView.qml
src/qml/Utils/ImageInputHandler.qml
src/qml/main.qml
src/src/declarative/pathviewrangehandler.cpp
src/src/declarative/pathviewrangehandler.h
src/src/globalcontrol.cpp
src/src/globalcontrol.h
src/src/globalstatus.cpp
src/src/globalstatus.h
src/src/imagedata/pathviewproxymodel.cpp
src/src/imagedata/pathviewproxymodel.h

[feat: image switching animation](https://github.com/linuxdeepin/deepin-image-viewer/commit/19571fac6e45336dd486b36c3c2b2cd4fc967470) 
Add image switching animation.
* Replace ListView to PathView;
* Add PathViewProxyModel to support ring data;
* Provides blur thumbnail while loading.
Log: Add image switching animation.
[feat: thumbnail switching animation](https://github.com/linuxdeepin/deepin-image-viewer/commit/ae8d0f4134bf78c128dacee96bee25b64ec0fc08) 
Add thumbnail switching animation
Log: Add thumbnail switching animation
Influence: Animation

feat: image and thumbnail switching animation

---

src/qml/ImageDelegate/BaseImageDelegate.qml
src/qml/ImageDelegate/NormalImageDelegate.qml
src/qml/ImageViewer.qml
src/qml/ThumbnailDelegate/NormalThumbnailDelegate.qml
src/qml/ThumbnailDelegate/ThumbnailImage.qml
src/src/globalcontrol.cpp
src/src/globalcontrol.h

* Image rotation animation;
* Thumbnail rotation animation.
Log: Add rotation animation.
Influence: Animation

feat: image rotation animation

---

src/deepin-image-viewer.qrc
src/main.cpp
src/qml/Dialog/RemoveDialog.qml
src/qml/ImageDelegate/BaseImageDelegate.qml
src/qml/ImageDelegate/NormalImageDelegate.qml
src/qml/ImageDelegate/ViewDelegateLoader.qml
src/qml/InformationDialog/ElideLabel.qml
src/qml/InformationDialog/InformationDialog.qml
src/qml/InformationDialog/PropertyActionItemDelegate.qml
src/qml/InformationDialog/PropertyItemDelegate.qml
src/qml/ReName.qml
src/qml/ThumbnailDelegate/NormalThumbnailDelegate.qml
src/qml/ThumbnailListView.qml
src/qml/ViewRightMenu.qml
src/qml/ViewTopTitle.qml
src/src/filecontrol.cpp
src/src/filecontrol.h
src/src/globalcontrol.cpp
src/src/globalcontrol.h
src/src/imagedata/imagefilewatcher.cpp
src/src/imagedata/imagefilewatcher.h
src/src/imagedata/imageinfo.cpp
src/src/imagedata/imageprovider.cpp
src/src/imagedata/imageprovider.h
src/src/imagedata/pathviewproxymodel.cpp
src/src/unionimage/unionimage.cpp
src/src/unionimage/unionimage.h
src/src/utils/rotateimagehelper.cpp
src/src/utils/rotateimagehelper.h

[fix: some animation errors](https://github.com/linuxdeepin/deepin-image-viewer/commit/db9fcc837e77547d5626e7a898c839594051c937) 
fix some animation errors.
* Animation component display wrong;
* Animation is not smooth enough under low performance;
* Move rotate image to thread;
* Adjust some component properties.
Log: fix some animation errors.
Bug: https://pms.uniontech.com/bug-view-268449.html,
https://pms.uniontech.com/bug-view-268441.html
Influence: Animation
[fix: info dialog adapt diff font size](https://github.com/linuxdeepin/deepin-image-viewer/commit/f331c75d6f0178c990177f23e068e952b2eb5e18) 
As title.
Log: Info dialog adapt diff font size.
Bug: https://pms.uniontech.com/bug-view-268607.html
[fix: image index wrong after …

fix: some animation and info dialog errors

---

src/qml/ImageDelegate/BaseImageDelegate.qml
src/qml/ImageDelegate/ViewDelegateLoader.qml
src/src/imagedata/pathviewproxymodel.cpp

As title.
Log: Fix some animation issue.
Bug: https://pms.uniontech.com/bug-view-270339.html

fix: only current item need blur

---

src/src/unionimage/baseutils.h
src/src/utils/filetrashhelper.cpp
src/src/utils/filetrashhelper.h

Adapt V25 dde-file-manager dbus service name changed
Log: Adapt V25 dde-file-manager dbus service name changed

chore: [dbus] Adapt V25 dde-file-manager dbus service name changed

---

debian/changelog

Bump version to 6.0.5
Log: Bump version to 6.0.5

chore: Bump version to 6.0.5

---

src/qml/ImageViewer.qml

As title, replace Control with Item.
Control steal mouse events.
Log: fix cannot drag window.
Bug: https://pms.uniontech.com/bug-view-269541.html

fix: cannot drag window with title bar

---

debian/changelog

Bump version to 6.0.7
Log: Bump version to 6.0.7

chore: Bump version to 6.0.7

---

debian/control
tests/CMakeLists.txt

rmove freeimage lib
Log: rmove freeimage lib
Task: https://pms.uniontech.com/task-view-365161.html

feat: rmove freeimage lib

---

README.md
README.zh_CN.md
debian/control
qimage-plugins/qimage-plugins.pro
src/CMakeLists.txt
src/src/imagedata/imageprovider.cpp
src/src/unionimage/baseutils.cpp
src/src/unionimage/imageutils.cpp
src/src/unionimage/unionimage.cpp
src/src/unionimage/unionimage.h

Remove the freeimage dependency
Log: Remove the freeimage dependency

fix: Remove the freeimage dependency

---

src/main.cpp
src/qml/ImageDelegate/BaseImageDelegate.qml
src/qml/ImageDelegate/NormalImageDelegate.qml
src/qml/ImageDelegate/ViewDelegateLoader.qml
src/qml/ThumbnailListView.qml
src/src/globalcontrol.cpp
src/src/imagedata/imageinfo.cpp
src/src/imagedata/imageprovider.cpp
src/src/imagedata/imageprovider.h
src/src/imagedata/pathviewproxymodel.cpp
src/src/imagedata/thumbnailcache.cpp
src/src/imagedata/thumbnailcache.h
src/src/unionimage/imageutils.cpp
src/src/unionimage/unionimage.cpp
src/src/unionimage/unionimage.h
src/src/utils/rotateimagehelper.cpp

Hide prevoius / next button when only single image.
Log: Hide btn when only single image.
Bug: https://pms.uniontech.com/bug-view-290687.html
Influence: UI
[fix: can not rotate after rename](https://github.com/linuxdeepin/deepin-image-viewer/pull/204/commits/1b7a28202906d627b3652e149887b1c31f271fd7) 
We add a new source model in the previous changes,
which not sync the name change, fix it.
Log: Fix can not rotate after rename.
Bug: https://pms.uniontech.com/bug-view-275403.html

fix: hide btn and fix rotate issue

---

debian/changelog
linglong.yaml

Bump version to 6.0.10
Log: Bump version to 6.0.10

chore: Bump version to 6.0.10

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.11
Log: Bump version to 6.0.11

chore: Bump version to 6.0.11

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.12
Log: Bump version to 6.0.12

chore: Bump version to 6.0.12

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml
src/CMakeLists.txt
src/misc/context-menus/deepin-print-pictures.conf

Adjust paths for linglong application.
Bump version to 6.0.13
Log: Adjust paths for linglong application
Bug: https://pms.uniontech.com/bug-view-303741.html

chore: Adjust paths for linglong application

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.14
Log: Bump version to 6.0.14

chore: Bump version to 6.0.14

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.15
Log: Bump version to 6.0.15

chore: Bump version to 6.0.15

---

arm64/linglong.yaml
linglong.yaml
loong64/linglong.yaml

Modify .service when build with linglong.
Log: fix can not start via dbus.

fix: can not start via dbus

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.16
Log: Bump version to 6.0.16

chore: Bump version to 6.0.16

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.17
Log: Bump version to 6.0.17

chore: Bump version to 6.0.17

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.18
Log: Bump version to 6.0.18

chore: Bump version to 6.0.18

---

.reuse/dep5
src/src/mainwindow/mainwindow.cpp

适配103x编译
task: https://pms.uniontech.com/task-view-365161.html
Log: 适配103x编译

fix: 适配103x编译

---

src/qml/LiveText/LiveTextWidget.qml

- Addressed blurry display in LiveText recognition.
- Fixed block width and height calculation errors.
- Ensured proper display at high zoom levels.
Log: Fixed blurry display in LiveText by correcting dimensions.

fix: Correct block dimensions and display issues in LiveText

---

src/qml/FullImageView.qml
src/qml/ImageDelegate/NormalImageDelegate.qml
src/qml/ImageViewer.qml
src/qml/MainStack.qml
src/qml/ThumbnailDelegate/NormalThumbnailDelegate.qml
src/qml/ThumbnailListView.qml
src/qml/ViewRightMenu.qml
src/qml/ViewTopTitle.qml
src/src/globalstatus.cpp
src/src/globalstatus.h

- Added delayInit for deferred initialization
- Converted components to async Loaders
- Refactored LiveText handling
- Improved menu/dialog loading
Log: Improved startup by deferring non-critical init.
Bug: https://pms.uniontech.com/bug-view-310383.html

refactor: Optimize loading with async Loaders

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.0.19
Log: Bump version to 6.0.19

chore: Bump version to 6.0.19

---

src/src/application.cpp

适配102x编译
Task: https://pms.uniontech.com/task-view-365161.html
Log: 适配102x编译

fix: 适配102x编译

---

src/qml/ImageViewer.qml

As title.
Log: fix a ui issue.

fix: Remove unnecessary code

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Release 6.0.20
Log: Release 6.0.20

fix: Release to unstable.

---

.gitignore
src/main.cpp
src/src/filecontrol.cpp
src/src/globalcontrol.cpp
src/src/imagedata/imagefilewatcher.cpp
src/src/imagedata/imageinfo.cpp
src/src/imagedata/imageprovider.cpp
src/src/imagedata/pathviewproxymodel.cpp
src/src/ocr/livetextanalyzer.cpp
src/src/printdialog/printhelper.cpp
src/src/unionimage/baseutils.cpp
src/src/unionimage/imageutils.cpp
src/src/unionimage/unionimage.cpp
src/src/utils/filetrashhelper.cpp
src/src/utils/rotateimagehelper.cpp

- Added logging capabilities using QLoggingCategory for better debugging.
- Introduced logging in various components including image loading, rotation, and file handling.
- Updated .gitignore to exclude .cursor files.
- Improved image path handling and error reporting in image-related functions.
Log: Enhanced logging for better traceability and debugging of image operations.

feat: Enhance logging and improve image handling

---

arm64/linglong.yaml
debian/changelog
debian/control
linglong.yaml
loong64/linglong.yaml

chore: update dependencies in configuration files
- Added libncnn-dev and libopencv-mobile-dev to the build dependencies for better support of image processing features.
- Updated linglong.yaml files for multiple architectures to include new source files for ncnn and opencv-mobile.
This change aims to enhance the functionality and compatibility of the project across different architectures.

  chore: update dependencies in configuration files 

---

.gitignore
src/main.cpp
src/src/commandparser.cpp
src/src/configsetter.cpp
src/src/cursortool.cpp
src/src/declarative/mousetrackitem.cpp
src/src/declarative/pathviewrangehandler.cpp
src/src/filecontrol.cpp
src/src/globalcontrol.cpp
src/src/globalstatus.cpp
src/src/imagedata/imagefilewatcher.cpp
src/src/imagedata/imageinfo.cpp
src/src/imagedata/imageprovider.cpp
src/src/imagedata/imagesourcemodel.cpp
src/src/imagedata/pathviewproxymodel.cpp
src/src/ocr/ocrinterface.cpp
src/src/printdialog/printhelper.cpp
src/src/types.cpp
src/src/unionimage/baseutils.cpp
src/src/unionimage/imageutils.cpp
src/src/unionimage/unionimage.cpp
src/src/utils/eventlogutils.cpp
src/src/utils/rotateimagehelper.cpp

Add more logs for AI tracking. 80.41%
Log: more logs.

chore: more logs

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

- update version to 6.0.27
log: update version to 6.0.27

chore: Update version to 6.0.27

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml
src/qml/ViewTopTitle.qml

as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-324119.html

fix: About interface application homepage display abnormality

---

arm64/linglong.yaml
debian/changelog
debian/control
deploy_dep
linglong.yaml
loong64/linglong.yaml
src/qml/MainStack.qml

Added support for HEIC, HEIF, and AVIF formats.
Log: new feature
Task: https://pms.uniontech.com/task-view-378959.html

feat: Image format extension support

---

src/src/unionimage/unionimage.cpp

Fixed CMYK image display issue
Log: Fixed CMYK image display issue
bug: https://pms.uniontech.com/bug-view-326991.html

fix: Fixed CMYK image display issue
